services:
  node1:
    build: .
    environment:
      - ADDRESS=:8080
      - PEERS=node2:8080,node3:8080
    ports:
      - "8081:8080"
  node2:
    build: .
    environment:
      - ADDRESS=:8080
      - PEERS=node1:8080,node3:8080
    ports:
      - "8082:8080"
  node3:
    build: .
    environment:
      - ADDRESS=:8080
      - PEERS=node1:8080,node2:8080
    ports:
      - "8083:8080"
